name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LHAPDF 6.2.3
      run: |
        wget 'https://lhapdf.hepforge.org/downloads/?f=LHAPDF-6.2.3.tar.gz' -O LHAPDF-6.2.3.tar.gz
        tar xzf LHAPDF-6.2.3.tar.gz
        cd LHAPDF-6.2.3
        ./configure --prefix=/usr
        make -j
        sudo make install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
