name: Rust

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install LHAPDF
      env:
        LHAPDF: LHAPDF-6.3.0
      run: |
        wget "https://lhapdf.hepforge.org/downloads/?f=${LHAPDF}.tar.gz" -O ${LHAPDF}.tar.gz
        tar xzf ${LHAPDF}.tar.gz
        cd ${LHAPDF}
        ./configure --prefix=${HOME}/prefix
        make -j
        make install
        echo "${HOME}/prefix/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${HOME}/prefix/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${HOME}/prefix/lib/pkgconfig" >> $GITHUB_ENV
        echo "PYTHONPATH=${HOME}/prefix/lib/python3.7/site-packages" >> $GITHUB_ENV
    - name: Install NNPDF31_nlo_as_0118_luxqed
      run: |
        lhapdf install NNPDF31_nlo_as_0118_luxqed
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          default: true
    - name: Run check
      run: cargo check --verbose
    - name: Generate doctest coverage
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: --ignore-tests
        run-types: Doctests,Tests
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
