name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install LHAPDF 6.3.0
      run: |
        wget 'https://lhapdf.hepforge.org/downloads/?f=LHAPDF-6.3.0.tar.gz' -O LHAPDF-6.3.0.tar.gz
        tar xzf LHAPDF-6.3.0.tar.gz
        cd LHAPDF-6.3.0
        ./configure --prefix=${HOME}/prefix
        make -j
        make install
        echo "${HOME}/prefix/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${HOME}/prefix/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${HOME}/prefix/lib/pkgconfig" >> $GITHUB_ENV
        echo "PYTHONPATH=${HOME}/prefix/lib/python3.7/site-packages" >> $GITHUB_ENV
    - name: Install NNPDF31_nlo_as_0118_luxqed
      run: |
        lhapdf install NNPDF31_nlo_as_0118_luxqed
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
